name: 'Validate PR name'
description: 'PR tooling for GitHub actions'
inputs:
  pr-name:
    description: the name of the PR
    required: true
    default: '${{ github.event.pull_request.title }}'
runs:
  using: 'docker'
  image: 'docker://cmser/git-tools'
  args:
    - git-tools
    - pr
    - validate
    - --name
    - "${{ inputs.pr-name }}"
