name: 'Create release branch'
description: 'PR tooling for GitHub actions'
inputs:
  pr-name:
    description: the name of the PR
    required: true
    default: '${{ github.event.pull_request.title }}'
  repo-id:
    description: the node_id of the repo for grapphql client
    required: true
    default: '${{ github.event.repository.node_id }}'
  token:
    description: the token used
    required: true
runs:
  using: 'docker'
  image: 'docker://cmser/git-tools'
  env:
    GITHUB_TOKEN: "${{ inputs.token }}"
  args:
    - git-tools
    - release
    - create
    - --name
    - "${{ inputs.pr-name }}"
