name: 'Create release branch'
description: 'PR tooling for GitHub actions'
inputs:
  pr-name:
    description: the name of the PR
    required: true
    default: '${{ github.event.pull_request.title }}'
  github-token:
    description: github token
    required: true
    default: '${{ github.token }}'
runs:
  using: 'docker'
  image: 'docker://cmser/git-tools'
  env:
    GITHUB_TOKEN: "${{ inputs.github-token }}"
  args:
    - git-tools
    - release
    - create
    - --name
    - "${{ inputs.pr-name }}"
