name: Create release branch

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:

  create_branch:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v2
      - uses: ./actions/release

