name: Create release

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
    branches:
      - 'feat/foo'

jobs:

  create_branch:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: create release
        uses: ./actions/release

