name: Create release

on: create

jobs:

  release:
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref, 'refs/heads/release/') }}
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Set output
        id: vars
        run: |
          tag=$(echo ${GITHUB_REF#refs/heads/} | cut -d/ -f2)
          echo ::set-output name=tag::$tag

      - name: Build the Docker image
        run: |
          docker build . --tag="cmser/git-tools:${{ steps.vars.outputs.tag }}"
          docker build . --tag="cmser/git-tools:latest"
      - name: Docker Push
        run: |
          docker push cmser/git-tools:${{ steps.vars.outputs.tag }}
          docker push cmser/git-tools:latest
